apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    field.cattle.io/creatorId: user-56c4l
  creationTimestamp: "2021-05-18T01:33:29Z"
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: statefulSet-default-test1
  name: test1
  namespace: default
  resourceVersion: "101512"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/test1
  uid: 0cc32874-b779-11eb-b51d-0a9d5ce8450c
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: statefulSet-default-test1
  serviceName: test1
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-05-18T01:33:29Z"
        field.cattle.io/excludeContainer: "false"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: statefulSet-default-test1
    spec:
      containers:
      - image: ubuntu:xenial
        imagePullPolicy: Always
        name: test1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: test1-7f56cbdb6f
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: test1-7f56cbdb6f
  updatedReplicas: 1
